package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"

	"github.com/Shelffy/shelffy/internal/api/apictx"
	"github.com/Shelffy/shelffy/internal/api/gql/gqlmodel"
	"github.com/Shelffy/shelffy/internal/api/gql/graph"
	"github.com/google/uuid"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlmodel.User, error) {
	userID, err := apictx.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	dbUser, err := r.UserService.GetByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return &gqlmodel.User{
		ID:        dbUser.ID,
		Email:     dbUser.Email,
		IsActive:  dbUser.IsActive,
		CreatedAt: dbUser.CreatedAt,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*gqlmodel.User, error) {
	dbUser, err := r.UserService.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return &gqlmodel.User{
		ID:        dbUser.ID,
		Email:     dbUser.Email,
		IsActive:  dbUser.IsActive,
		CreatedAt: dbUser.CreatedAt,
	}, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
